

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Acknowledgemet_of_Accountability_Form" (
    "accountabilityForm" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "timestamp" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studentNumber" "text",
    "roomNumber" "text",
    "roomKey_propertyNumber" "text",
    "studyTable_propertyNumber" "text",
    "jalousies_propertyNumber" "text",
    "window_propertyNumber" "text",
    "bedfoam_propertyNumber" "text",
    "closet_propertyNumber" "text",
    "ClosetDoorHandle_propertyNumber" "text",
    "chair_propertyNumber" "text",
    "semester" smallint,
    "isArchived" boolean DEFAULT false
);


ALTER TABLE "public"."Acknowledgemet_of_Accountability_Form" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Application_for_Dorm_Accomodation" (
    "studentNumber" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Sex" "text",
    "Age" integer,
    "Course" "text",
    "yearLevel" integer,
    "dateOfBirth" "date",
    "placeOfBirth" "text",
    "religion" "text",
    "civilStatus" "text",
    "nationality" "text",
    "emailAddress" "text",
    "homeAddress" "text",
    "contactNo" "text",
    "isStayedInAnyDormitory" boolean,
    "lengthOfStay" "text",
    "whereStayed" "text",
    "admissionYear" "text",
    "semester_of_admissionYear" "text",
    "studentName" "text"
);


ALTER TABLE "public"."Application_for_Dorm_Accomodation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Designated_Guardians" (
    "designatedGuardianID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "fullName_of_Guardian" "text" NOT NULL,
    "relationshipToResident" "text",
    "completeAddress" "text",
    "contactNumber" "text",
    "studentNumber" "text"
);


ALTER TABLE "public"."Designated_Guardians" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Information_and_Instruction_Sheet" (
    "studentNumber" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Allowed_ToGoHomeInWeekends" "text",
    "Allowed_ToGoHomeInWeekdays" "text",
    "isAllowed_WeekendsWithRelatives_or_guardians" boolean,
    "isAllowed_spendOvernightWithFriends_or_dormmates" boolean,
    "isAllowed_joinSchoolRelatedFieldTripsOrPicnicsOrExcursions" boolean,
    "isAllowed_joinOrganizations" boolean,
    "isAllowed_joinDemonstrations_or_rallies" boolean,
    "whatIllnesses" "text",
    "otherAdditionalInstruction" "text"
);


ALTER TABLE "public"."Information_and_Instruction_Sheet" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."List_of_Offenses" (
    "offenseID" bigint NOT NULL,
    "offenseName" "text",
    "offenseSeverity" "text"
);


ALTER TABLE "public"."List_of_Offenses" OWNER TO "postgres";


COMMENT ON TABLE "public"."List_of_Offenses" IS 'This will have the list of all offenes';



ALTER TABLE "public"."List_of_Offenses" ALTER COLUMN "offenseID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."List_of_Offenses_offenseID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Offenses_Occured" (
    "offenceInstance" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "studentNumber" "text" NOT NULL,
    "offenseID" bigint NOT NULL,
    "timestamp" "date" DEFAULT "now"(),
    "adminName" "text" NOT NULL
);


ALTER TABLE "public"."Offenses_Occured" OWNER TO "postgres";


COMMENT ON TABLE "public"."Offenses_Occured" IS 'This will contain all of offenses instances';



CREATE TABLE IF NOT EXISTS "public"."Overnight_Excuse" (
    "overnightExcuseID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "approvedby_adminID" "uuid",
    "validatedby_adminID" "uuid",
    "fromDate" timestamp with time zone NOT NULL,
    "toDate" timestamp with time zone NOT NULL,
    "approvedOn" timestamp with time zone,
    "validatedOn" timestamp with time zone,
    "sentOn" timestamp with time zone DEFAULT "now"(),
    "isValidated" boolean,
    "isApproved" boolean,
    "studentNumber" "text",
    "reason" "text" NOT NULL
);


ALTER TABLE "public"."Overnight_Excuse" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Students" (
    "studentNumber" "text" NOT NULL,
    "userID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "isAssessed" boolean DEFAULT false,
    "isArchived" boolean DEFAULT false,
    "timstamp" timestamp with time zone DEFAULT "now"(),
    "surplus_deficit_payment" double precision DEFAULT '0'::double precision,
    "studentName" "text",
    "email" character varying,
    "latest_announcement" bigint
);


ALTER TABLE "public"."Students" OWNER TO "postgres";


COMMENT ON TABLE "public"."Students" IS 'This table will be the masterlist of all students';



CREATE TABLE IF NOT EXISTS "public"."Transient" (
    "transientID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "userID" "uuid" NOT NULL,
    "nameOfOccupant" "text" DEFAULT ''::"text",
    "completeAddress" "text" DEFAULT 'NULL'::"text",
    "contactNumber" "text" DEFAULT 'NULL'::"text",
    "agencyConnected" "text" DEFAULT 'NULL'::"text",
    "emergencyContact" "text",
    "isAccepted" boolean DEFAULT false,
    "timestamp" timestamp with time zone DEFAULT "now"(),
    "email" "text"
);


ALTER TABLE "public"."Transient" OWNER TO "postgres";


COMMENT ON TABLE "public"."Transient" IS 'This will be the table for the transients';



CREATE TABLE IF NOT EXISTS "public"."Transient_Request" (
    "transientID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "requestDateFrom" "date" NOT NULL,
    "requestDateTo" "date" NOT NULL,
    "no_Males" smallint,
    "no_Females" smallint,
    "purposeOfStay" "text" NOT NULL,
    "isBedding_and_Towel" boolean NOT NULL,
    "timestamp" timestamp without time zone DEFAULT "now"() NOT NULL,
    "isSigned" boolean DEFAULT false NOT NULL,
    "isCash" boolean DEFAULT false NOT NULL,
    "isWaived" boolean DEFAULT false NOT NULL,
    "isEBL" boolean,
    "isILC" boolean,
    "requestID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."Transient_Request" OWNER TO "postgres";


COMMENT ON TABLE "public"."Transient_Request" IS 'This will contain every request of every person';



CREATE TABLE IF NOT EXISTS "public"."admin" (
    "adminID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "adminName" "text" DEFAULT 'NULL'::"text" NOT NULL,
    "userID" "uuid" DEFAULT "gen_random_uuid"(),
    "isAccepted" boolean,
    "timstamp" timestamp with time zone DEFAULT "now"(),
    "email" "text"
);


ALTER TABLE "public"."admin" OWNER TO "postgres";


COMMENT ON TABLE "public"."admin" IS 'This will contain all of the necessary information about the admins';



CREATE OR REPLACE VIEW "public"."admin_accepted_users" AS
 SELECT "a"."adminID",
    "a"."userID"
   FROM "public"."admin" "a"
  WHERE ("a"."isAccepted" = true);


ALTER TABLE "public"."admin_accepted_users" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_requests_summary" AS
 SELECT "s"."userID" AS "request_unique_id",
    'student'::"text" AS "requester_type",
    "s"."studentName" AS "requester_name",
    "s"."isAssessed" AS "request_status_boolean",
    "s"."timstamp" AS "request_timestamp",
    "s"."userID" AS "original_entity_id"
   FROM "public"."Students" "s"
UNION ALL
 SELECT "t"."userID" AS "request_unique_id",
    'transient'::"text" AS "requester_type",
    "t"."nameOfOccupant" AS "requester_name",
    "t"."isAccepted" AS "request_status_boolean",
    "t"."timestamp" AS "request_timestamp",
    "t"."userID" AS "original_entity_id"
   FROM "public"."Transient" "t"
UNION ALL
 SELECT "a"."userID" AS "request_unique_id",
    'admin'::"text" AS "requester_type",
    "a"."adminName" AS "requester_name",
    "a"."isAccepted" AS "request_status_boolean",
    "a"."timstamp" AS "request_timestamp",
    "a"."userID" AS "original_entity_id"
   FROM "public"."admin" "a";


ALTER TABLE "public"."all_requests_summary" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."appliance_per_student" (
    "applianceOwned" bigint NOT NULL,
    "applianceID" bigint NOT NULL,
    "studentNumber" "text",
    "quantity" integer,
    "serialNo" "text",
    "brand" "text",
    "isActive" boolean
);


ALTER TABLE "public"."appliance_per_student" OWNER TO "postgres";


COMMENT ON COLUMN "public"."appliance_per_student"."isActive" IS 'This will determine if this billing should be included or not';



ALTER TABLE "public"."appliance_per_student" ALTER COLUMN "applianceOwned" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."appliance_per_student_applianceOwned_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."guardianInformation" (
    "guardianID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studentNumber" "text",
    "guardianType" "text",
    "Name" "text",
    "Occupation" "text",
    "Age" integer,
    "businessAddress_or_employmentAddress" "text",
    "contactNumber" "text"
);


ALTER TABLE "public"."guardianInformation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."list_of_appliances" (
    "applianceID" bigint NOT NULL,
    "applianceName" "text" NOT NULL,
    "cost" double precision
);


ALTER TABLE "public"."list_of_appliances" OWNER TO "postgres";


ALTER TABLE "public"."list_of_appliances" ALTER COLUMN "applianceID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."list_of_appliances_applianceID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."signatureTable" (
    "signatureID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userID" "uuid" DEFAULT "gen_random_uuid"(),
    "formName" "text",
    "isAgreed" "text",
    "role" "text",
    "expirationDate" "date"
);


ALTER TABLE "public"."signatureTable" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."staticCharge" (
    "staticChargeID" bigint NOT NULL,
    "chargeName" "text" NOT NULL,
    "charge" double precision
);


ALTER TABLE "public"."staticCharge" OWNER TO "postgres";


ALTER TABLE "public"."staticCharge" ALTER COLUMN "staticChargeID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."staticCharge_staticChargeID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."studentCharge" (
    "chargeID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "timestamp" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studentNumber" "text",
    "amount" double precision,
    "dueDate" "date",
    "adminID" "uuid" DEFAULT "gen_random_uuid"()
);


ALTER TABLE "public"."studentCharge" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."studentPayment" (
    "paymentID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "timestamp" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studentNumber" "text",
    "adminID" "uuid",
    "paymentAmount" double precision NOT NULL,
    "referenceID" "text"
);


ALTER TABLE "public"."studentPayment" OWNER TO "postgres";


ALTER TABLE ONLY "public"."Acknowledgemet_of_Accountability_Form"
    ADD CONSTRAINT "Acknowledgemet_of_Accountability_Form_pkey" PRIMARY KEY ("accountabilityForm");



ALTER TABLE ONLY "public"."Application_for_Dorm_Accomodation"
    ADD CONSTRAINT "Application_for_Dorm_Accomodation_pkey" PRIMARY KEY ("studentNumber");



ALTER TABLE ONLY "public"."Designated_Guardians"
    ADD CONSTRAINT "Designated_Guardians_pkey" PRIMARY KEY ("designatedGuardianID");



ALTER TABLE ONLY "public"."Information_and_Instruction_Sheet"
    ADD CONSTRAINT "Information_and_Instruction_Sheet_pkey" PRIMARY KEY ("studentNumber");



ALTER TABLE ONLY "public"."List_of_Offenses"
    ADD CONSTRAINT "List_of_Offenses_pkey" PRIMARY KEY ("offenseID");



ALTER TABLE ONLY "public"."Offenses_Occured"
    ADD CONSTRAINT "Offenses_Occured_pkey" PRIMARY KEY ("offenceInstance", "studentNumber", "offenseID", "adminName");



ALTER TABLE ONLY "public"."Overnight_Excuse"
    ADD CONSTRAINT "Overnight_Excuse_pkey" PRIMARY KEY ("overnightExcuseID");



ALTER TABLE ONLY "public"."Students"
    ADD CONSTRAINT "Students_pkey" PRIMARY KEY ("studentNumber");



ALTER TABLE ONLY "public"."Transient_Request"
    ADD CONSTRAINT "Transient_Request_pkey" PRIMARY KEY ("requestID");



ALTER TABLE ONLY "public"."Transient"
    ADD CONSTRAINT "Transient_pkey" PRIMARY KEY ("transientID");



ALTER TABLE ONLY "public"."admin"
    ADD CONSTRAINT "admin_pkey" PRIMARY KEY ("adminID");



ALTER TABLE ONLY "public"."appliance_per_student"
    ADD CONSTRAINT "appliance_per_student_pkey" PRIMARY KEY ("applianceOwned");



ALTER TABLE ONLY "public"."guardianInformation"
    ADD CONSTRAINT "guardianInformation_pkey" PRIMARY KEY ("guardianID");



ALTER TABLE ONLY "public"."list_of_appliances"
    ADD CONSTRAINT "list_of_appliances_pkey" PRIMARY KEY ("applianceID");



ALTER TABLE ONLY "public"."signatureTable"
    ADD CONSTRAINT "signatureTable_pkey" PRIMARY KEY ("signatureID");



ALTER TABLE ONLY "public"."staticCharge"
    ADD CONSTRAINT "staticCharge_pkey" PRIMARY KEY ("staticChargeID");



ALTER TABLE ONLY "public"."studentCharge"
    ADD CONSTRAINT "studentCharge_pkey" PRIMARY KEY ("chargeID");



ALTER TABLE ONLY "public"."studentPayment"
    ADD CONSTRAINT "studentPayment_pkey" PRIMARY KEY ("paymentID");



ALTER TABLE ONLY "public"."Acknowledgemet_of_Accountability_Form"
    ADD CONSTRAINT "Acknowledgemet_of_Accountability_Form_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Application_for_Dorm_Accomodation"
    ADD CONSTRAINT "Application_for_Dorm_Accomodation_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Designated_Guardians"
    ADD CONSTRAINT "Designated_Guardians_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Information_and_Instruction_Sheet"
    ADD CONSTRAINT "Information_and_Instruction_Sheet_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Offenses_Occured"
    ADD CONSTRAINT "Offenses_Occured_offenseID_fkey" FOREIGN KEY ("offenseID") REFERENCES "public"."List_of_Offenses"("offenseID") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Offenses_Occured"
    ADD CONSTRAINT "Offenses_Occured_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Overnight_Excuse"
    ADD CONSTRAINT "Overnight_Excuse_approvedby_adminID_fkey" FOREIGN KEY ("approvedby_adminID") REFERENCES "public"."admin"("adminID") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Overnight_Excuse"
    ADD CONSTRAINT "Overnight_Excuse_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Overnight_Excuse"
    ADD CONSTRAINT "Overnight_Excuse_validatedby_adminID_fkey" FOREIGN KEY ("validatedby_adminID") REFERENCES "public"."admin"("adminID") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Students"
    ADD CONSTRAINT "Students_userID_fkey" FOREIGN KEY ("userID") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Transient_Request"
    ADD CONSTRAINT "Transient_Request_transientID_fkey" FOREIGN KEY ("transientID") REFERENCES "public"."Transient"("transientID") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Transient"
    ADD CONSTRAINT "Transient_userID_fkey" FOREIGN KEY ("userID") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."admin"
    ADD CONSTRAINT "admin_userID_fkey" FOREIGN KEY ("userID") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."appliance_per_student"
    ADD CONSTRAINT "appliance_per_student_applianceID_fkey" FOREIGN KEY ("applianceID") REFERENCES "public"."list_of_appliances"("applianceID") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."appliance_per_student"
    ADD CONSTRAINT "appliance_per_student_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."guardianInformation"
    ADD CONSTRAINT "guardianInformation_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."signatureTable"
    ADD CONSTRAINT "signatureTable_userID_fkey" FOREIGN KEY ("userID") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studentCharge"
    ADD CONSTRAINT "studentCharge_adminID_fkey" FOREIGN KEY ("adminID") REFERENCES "public"."admin"("adminID") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."studentCharge"
    ADD CONSTRAINT "studentCharge_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studentPayment"
    ADD CONSTRAINT "studentPayment_adminID_fkey" FOREIGN KEY ("adminID") REFERENCES "public"."admin"("adminID") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."studentPayment"
    ADD CONSTRAINT "studentPayment_studentNumber_fkey" FOREIGN KEY ("studentNumber") REFERENCES "public"."Students"("studentNumber") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."Acknowledgemet_of_Accountability_Form" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Admin can do  anything" ON "public"."Application_for_Dorm_Accomodation" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."Acknowledgemet_of_Accountability_Form" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."Designated_Guardians" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true)))));



CREATE POLICY "Admin can do anything" ON "public"."Information_and_Instruction_Sheet" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."List_of_Offenses" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."Offenses_Occured" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."Overnight_Excuse" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."Students" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE ("admin"."userID" = "auth"."uid"())))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."appliance_per_student" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."guardianInformation" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."list_of_appliances" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."staticCharge" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."studentCharge" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can do anything" ON "public"."studentPayment" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true))))) WITH CHECK (true);



CREATE POLICY "Admin can see everything" ON "public"."signatureTable" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE (("admin"."userID" = "auth"."uid"()) AND ("admin"."isAccepted" = true)))));



CREATE POLICY "Any student can insert" ON "public"."Acknowledgemet_of_Accountability_Form" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."isAssessed" = true) AND ("Students"."isArchived" = false)))));



CREATE POLICY "Any student can insert" ON "public"."Overnight_Excuse" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."isAssessed" = true)))));



CREATE POLICY "Any student can see their own" ON "public"."Designated_Guardians" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."studentNumber" = "Designated_Guardians"."studentNumber")))));



CREATE POLICY "Any student can view their own." ON "public"."Acknowledgemet_of_Accountability_Form" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."studentNumber" = "Acknowledgemet_of_Accountability_Form"."studentNumber")))));



CREATE POLICY "Anyone can add" ON "public"."Designated_Guardians" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Anyone can add their own info" ON "public"."guardianInformation" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Anyone can add their own information" ON "public"."Students" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Anyone can see" ON "public"."admin" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Anyone can see" ON "public"."staticCharge" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Anyone can see their own" ON "public"."Offenses_Occured" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."isAssessed" = true) AND ("Students"."studentNumber" = "Offenses_Occured"."studentNumber")))));



CREATE POLICY "Anyone can view their own row" ON "public"."Application_for_Dorm_Accomodation" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."studentNumber" = "Application_for_Dorm_Accomodation"."studentNumber")))));



ALTER TABLE "public"."Application_for_Dorm_Accomodation" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Can delete their own" ON "public"."appliance_per_student" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."isAssessed" = true) AND ("appliance_per_student"."studentNumber" = "Students"."studentNumber")))));



ALTER TABLE "public"."Designated_Guardians" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable everyone to be transient" ON "public"."Transient" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable everything for all admin" ON "public"."Transient" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."admin"
  WHERE ("admin"."userID" = "auth"."uid"())))) WITH CHECK (true);



CREATE POLICY "Enable user to view their own info" ON "public"."Transient" FOR SELECT TO "authenticated" USING (("userID" = "auth"."uid"()));



CREATE POLICY "Enable users to Update their info" ON "public"."Transient" FOR UPDATE TO "authenticated" USING (("userID" = "auth"."uid"())) WITH CHECK ((("userID" = "auth"."uid"()) AND ("transientID" = "transientID") AND ("isAccepted" = "isAccepted")));



CREATE POLICY "Enable users to see their own requests" ON "public"."Transient_Request" FOR SELECT TO "authenticated" USING (("transientID" IN ( SELECT "Transient"."transientID"
   FROM "public"."Transient"
  WHERE ("Transient"."userID" = "auth"."uid"()))));



CREATE POLICY "Enable users to submit their own" ON "public"."Transient_Request" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Every one can submit" ON "public"."signatureTable" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Everyone can see their own signature" ON "public"."signatureTable" FOR SELECT USING (("userID" = "auth"."uid"()));



ALTER TABLE "public"."Information_and_Instruction_Sheet" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."List_of_Offenses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Offenses_Occured" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Only admin can do other stuff" ON "public"."admin" TO "authenticated" USING (("userID" IN ( SELECT "admin_accepted_users"."userID"
   FROM "public"."admin_accepted_users"))) WITH CHECK (("userID" IN ( SELECT "admin_accepted_users"."userID"
   FROM "public"."admin_accepted_users")));



ALTER TABLE "public"."Overnight_Excuse" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Student can see their statuses" ON "public"."Overnight_Excuse" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."isAssessed" = true) AND ("Overnight_Excuse"."studentNumber" = "Students"."studentNumber")))));



ALTER TABLE "public"."Students" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Students Can see their own information" ON "public"."guardianInformation" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."studentNumber" = "guardianInformation"."studentNumber")))));



CREATE POLICY "Students can only see their own information" ON "public"."appliance_per_student" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."studentNumber" = "appliance_per_student"."studentNumber")))));



CREATE POLICY "Students can see" ON "public"."List_of_Offenses" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."isAssessed" = true)))));



CREATE POLICY "Students can see their own info" ON "public"."Information_and_Instruction_Sheet" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."studentNumber" = "Information_and_Instruction_Sheet"."studentNumber")))));



CREATE POLICY "Students can see their own info" ON "public"."Students" FOR SELECT TO "authenticated" USING (("userID" = "auth"."uid"()));



ALTER TABLE "public"."Transient" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Transient_Request" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."admin" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "any  student can see their own" ON "public"."studentCharge" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."Students"
  WHERE (("Students"."userID" = "auth"."uid"()) AND ("Students"."studentNumber" = "studentCharge"."studentNumber") AND ("Students"."isAssessed" = true)))));



CREATE POLICY "anyone can add" ON "public"."Information_and_Instruction_Sheet" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "anyone can add" ON "public"."admin" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "anyone can add" ON "public"."appliance_per_student" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "anyone can see" ON "public"."list_of_appliances" FOR SELECT USING (true);



ALTER TABLE "public"."appliance_per_student" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "authenticated user can insert" ON "public"."Application_for_Dorm_Accomodation" FOR INSERT TO "authenticated" WITH CHECK (true);



ALTER TABLE "public"."guardianInformation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."list_of_appliances" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."signatureTable" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."staticCharge" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."studentCharge" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."studentPayment" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."Acknowledgemet_of_Accountability_Form" TO "anon";
GRANT ALL ON TABLE "public"."Acknowledgemet_of_Accountability_Form" TO "authenticated";
GRANT ALL ON TABLE "public"."Acknowledgemet_of_Accountability_Form" TO "service_role";



GRANT ALL ON TABLE "public"."Application_for_Dorm_Accomodation" TO "anon";
GRANT ALL ON TABLE "public"."Application_for_Dorm_Accomodation" TO "authenticated";
GRANT ALL ON TABLE "public"."Application_for_Dorm_Accomodation" TO "service_role";



GRANT ALL ON TABLE "public"."Designated_Guardians" TO "anon";
GRANT ALL ON TABLE "public"."Designated_Guardians" TO "authenticated";
GRANT ALL ON TABLE "public"."Designated_Guardians" TO "service_role";



GRANT ALL ON TABLE "public"."Information_and_Instruction_Sheet" TO "anon";
GRANT ALL ON TABLE "public"."Information_and_Instruction_Sheet" TO "authenticated";
GRANT ALL ON TABLE "public"."Information_and_Instruction_Sheet" TO "service_role";



GRANT ALL ON TABLE "public"."List_of_Offenses" TO "anon";
GRANT ALL ON TABLE "public"."List_of_Offenses" TO "authenticated";
GRANT ALL ON TABLE "public"."List_of_Offenses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."List_of_Offenses_offenseID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."List_of_Offenses_offenseID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."List_of_Offenses_offenseID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Offenses_Occured" TO "anon";
GRANT ALL ON TABLE "public"."Offenses_Occured" TO "authenticated";
GRANT ALL ON TABLE "public"."Offenses_Occured" TO "service_role";



GRANT ALL ON TABLE "public"."Overnight_Excuse" TO "anon";
GRANT ALL ON TABLE "public"."Overnight_Excuse" TO "authenticated";
GRANT ALL ON TABLE "public"."Overnight_Excuse" TO "service_role";



GRANT ALL ON TABLE "public"."Students" TO "anon";
GRANT ALL ON TABLE "public"."Students" TO "authenticated";
GRANT ALL ON TABLE "public"."Students" TO "service_role";



GRANT ALL ON TABLE "public"."Transient" TO "anon";
GRANT ALL ON TABLE "public"."Transient" TO "authenticated";
GRANT ALL ON TABLE "public"."Transient" TO "service_role";



GRANT ALL ON TABLE "public"."Transient_Request" TO "anon";
GRANT ALL ON TABLE "public"."Transient_Request" TO "authenticated";
GRANT ALL ON TABLE "public"."Transient_Request" TO "service_role";



GRANT ALL ON TABLE "public"."admin" TO "anon";
GRANT ALL ON TABLE "public"."admin" TO "authenticated";
GRANT ALL ON TABLE "public"."admin" TO "service_role";



GRANT ALL ON TABLE "public"."admin_accepted_users" TO "anon";
GRANT ALL ON TABLE "public"."admin_accepted_users" TO "authenticated";
GRANT ALL ON TABLE "public"."admin_accepted_users" TO "service_role";



GRANT ALL ON TABLE "public"."all_requests_summary" TO "anon";
GRANT ALL ON TABLE "public"."all_requests_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."all_requests_summary" TO "service_role";



GRANT ALL ON TABLE "public"."appliance_per_student" TO "anon";
GRANT ALL ON TABLE "public"."appliance_per_student" TO "authenticated";
GRANT ALL ON TABLE "public"."appliance_per_student" TO "service_role";



GRANT ALL ON SEQUENCE "public"."appliance_per_student_applianceOwned_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."appliance_per_student_applianceOwned_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."appliance_per_student_applianceOwned_seq" TO "service_role";



GRANT ALL ON TABLE "public"."guardianInformation" TO "anon";
GRANT ALL ON TABLE "public"."guardianInformation" TO "authenticated";
GRANT ALL ON TABLE "public"."guardianInformation" TO "service_role";



GRANT ALL ON TABLE "public"."list_of_appliances" TO "anon";
GRANT ALL ON TABLE "public"."list_of_appliances" TO "authenticated";
GRANT ALL ON TABLE "public"."list_of_appliances" TO "service_role";



GRANT ALL ON SEQUENCE "public"."list_of_appliances_applianceID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."list_of_appliances_applianceID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."list_of_appliances_applianceID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."signatureTable" TO "anon";
GRANT ALL ON TABLE "public"."signatureTable" TO "authenticated";
GRANT ALL ON TABLE "public"."signatureTable" TO "service_role";



GRANT ALL ON TABLE "public"."staticCharge" TO "anon";
GRANT ALL ON TABLE "public"."staticCharge" TO "authenticated";
GRANT ALL ON TABLE "public"."staticCharge" TO "service_role";



GRANT ALL ON SEQUENCE "public"."staticCharge_staticChargeID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."staticCharge_staticChargeID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."staticCharge_staticChargeID_seq" TO "service_role";



GRANT ALL ON TABLE "public"."studentCharge" TO "anon";
GRANT ALL ON TABLE "public"."studentCharge" TO "authenticated";
GRANT ALL ON TABLE "public"."studentCharge" TO "service_role";



GRANT ALL ON TABLE "public"."studentPayment" TO "anon";
GRANT ALL ON TABLE "public"."studentPayment" TO "authenticated";
GRANT ALL ON TABLE "public"."studentPayment" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






